[workspace]
members = ["laurus"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
description = "Unified search library for lexical, vector, and semantic retrieval"
documentation = "https://docs.rs/laurus"
homepage = "https://github.com/mosuka/laurus"
repository = "https://github.com/mosuka/laurus"
readme = "README.md"
keywords = ["search", "vector", "lexical", "hybrid", "library"]
categories = ["text-processing"]
license = "MIT"

[workspace.dependencies]
laurus = { version = "0.1.0", path = "laurus" }

[profile.release]
lto = true
