[book]
authors = ["Mosuka"]
language = "en"
multilingual = false
src = "src"
title = "Sarissa Documentation"

[output.html]
git-repository-url = "https://github.com/mosuka/sarissa"
site-url = "/sarissa/"
