[book]
authors = ["Minoru Osuka"]
language = "en"
src = "src"
title = "Iris Documentation"

[output.html]
git-repository-url = "https://github.com/mosuka/iris"
site-url = "/iris/"

additional-js = ["mermaid.min.js", "mermaid-init.js"]
