[book]
authors = ["Minoru Osuka"]
language = "en"
src = "src"
title = "Laurus Documentation"

[output.html]
git-repository-url = "https://github.com/mosuka/laurus"
site-url = "/laurus/"

additional-js = ["mermaid.min.js", "mermaid-init.js"]
